<template>
  <div class=" text-zinc-800 dark:bg-zinc-800 dark:text-zinc-100">
    <title>Haneko | My Porfolio</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>